# https://github.com/authelia/authelia/blob/v4.37.5/config.template.yml
---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: http://authelia.127.0.0.1.xip.io:9091

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.127.0.0.1.xip.io

authentication_backend:
  # file:
  #   path: /config/users_database.yml
  ldap:
    url: ldap://127.0.0.1:10389
    base_dn: dc=example,dc=com
    username_attribute: uid
    additional_users_dn: ou=users
    # users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    # (&(uniqueMember={dn})(objectClass=groupOfUniqueNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    # permit_referrals: false
    user: cn=admin,dc=example,dc=com
    password: password

access_control:
  default_policy: deny
  rules:
    - domain: public.authelia.127.0.0.1.xip.io
      policy: bypass
    - domain: traefik.authelia.127.0.0.1.xip.io
      policy: one_factor
    - domain: secure.authelia.127.0.0.1.xip.io
      policy: two_factor

session:
  secret: unsecure_session_secret
  domain: authelia.127.0.0.1.xip.io

#   cookies:
#     - name: authelia_session
#       domain: authelia.127.0.0.1.xip.io # Should match whatever your root protected domain is
#       expiration: 3600 # 1 hour
#       inactivity: 300 # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /tmp/authelia-db.sqlite3

notifier:
  filesystem:
    filename: /tmp/authelia-notification.txt
